/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-08-31 08:25:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.m;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/m/./top.jsp", Long.valueOf(1693470331653L));
    _jspx_dependants.put("/m/./copyright.jsp", Long.valueOf(1693462617366L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>모바일 로그인 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("	function login() {\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write('\r');
      out.write('\n');

	String user_id = "";
	String user_name = "";
	try{

		user_id = (String) session.getAttribute("perid");
		user_name = (String) session.getAttribute("pernm");
		/*
		user_id = String.valueOf(session.getAttribute("perid"));
		user_name = String.valueOf(session.getAttribute("pernm"));
		*/
	}
	catch(Exception e){
		
	}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function gopage() {\r\n");
      out.write("		location.href='./login.jsp';\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<div>\r\n");
 if(user_id == "" || user_id == null) { 
      out.write("\r\n");
      out.write("<span onclick=\"gopage()\">로그인</span>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<span>");
      out.print(user_name);
      out.write("님 환영합니다. <a href=\"./mlogout.jsp\">[로그아웃]</a>\r\n");
      out.write("\r\n");
      out.write("</span>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</header>	<!-- 메뉴 또는 로그인 -->\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("<form name=\"f\" method=\"post\" action=\"./mlogin.do\">\r\n");
      out.write("<section>\r\n");
      out.write("	<p>MEMBER-LOGIN</p>\r\n");
      out.write("	아이디 : <input type=\"text\" name=\"mid\" required=\"required\"><br>\r\n");
      out.write("	패스워드 : <input type=\"password\" name=\"mpass\" required=\"required\"><br>\r\n");
      out.write("	<button type=\"submit\">로그인</button>\r\n");
      out.write("</section>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<footer>			<!-- copyright -->\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("하단\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	var id = \"");
      out.print(user_id);
      out.write("\";\r\n");
      out.write("	var nm = \"");
      out.print(user_name);
      out.write("\";\r\n");
      out.write("	\r\n");
      out.write("	if(id != \"null\" || nm != \"null\"){\r\n");
      out.write("		location.href=\"./index2.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
